### ISSUE TITLE
Browser is completely transparent after configuration

### ISSUE THREAD

**Issue by perry-mitchell** [JamieMason/devtools-extension-tab-colours#1]
I run two profiles at once, and after applying the steps detailed on the plugin page, all at once, and then reloading, I'm presented with one window like so:

![image](https://cloud.githubusercontent.com/assets/3869469/20268697/e8434618-aa88-11e6-8829-8888b57cc8e3.png)

It's always reproducible. If I perform the steps on both browsers at the same time, the experimental settings in devtools is not available. If it weren't for the other window I'd probably not be able to undo the experimental setting.

I'm using Ubuntu 16.04, Chrome 54.0.2840.71 (64-bit).

**Comment by JamieMason** [comment]
Hey @perry-mitchell, does this happen when the extension isn't installed? But the experimental flags are enabled?

**Comment by perry-mitchell** [comment]
@JamieMason yes, upon repeating the steps without the extension it still occurs.

Would be fantastic if someone else on Ubuntu could confirm if this occurs for them.

**Comment by JamieMason** [comment]
Sorry this isn't very helpful @perry-mitchell, but all I can suggest is to check the [chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) for issues related to that experimental flag. All this extension really does is [embed a stylesheet](https://github.com/JamieMason/devtools-extension-tab-colours/blob/master/devtools.js) so there's nothing that can be done here AFAIK.

**Comment by JamieMason** [comment]
(long shot but if you have the Material Design experiment enabled, try it with that off – I seem to remember enabling that some time ago and ran into a lot of problems).
