### ISSUE TITLE
Breaking bookmarks icons 

### ISSUE THREAD

**Issue by selfrefactor** [JamieMason/devtools-extension-tab-colours#4]
Environment: 
Ubuntu 16.04 64bit
Browser- Chromium v54

After all the steps, the icons of my Google bookmarks disappeared. When I took the steps back, my icons behavior was restored.

The idea of the extension is nice, but as person who uses daily his bookmarks, this is a blocking bug.

**Comment by JamieMason** [comment]
Hey @selfrefactor, does this happen when the extension isn't installed? But the experimental flags are enabled?

**Comment by selfrefactor** [comment]
So I installed first the extension, then changed the flags and finally set developer tools settings. Extension itself works, but as I said there was a price in my case. I haven't read your code, but I would bet that this is rather bug with Chromium, rather than the extension. That was the reason to close the issue. Btw, thank you for the fast response.

**Comment by JamieMason** [comment]
thanks @selfrefactor, sorry it didn't work for you.
